apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flask-server
  name: flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: flask-server
    spec:
      containers:
      - image: rapidfort/flaskapp:latest
        name: flask
        ports:
        - containerPort: 5000
          protocol: TCP
      imagePullSecrets:
      - name: docker-edu-secret
